[package]
name = "helloworld-script"
type = "script"
version = "0.1.0"
maintainers = ["Emin Fedar <eminfedar@gmail.com>"]

homepage = "https://pardus.org.tr"
source_repository = "https://github.com/repo-here/if-exists"
keywords = ["package", "tags", "here"]
categories = ["Game", "Education"]

license = "MIT"
architectures = ["any"]

description = """
Multiline description of what this package is about.
"""

[dependencies.application]
python3 = "3.11"
python3-gi = "3.42"

[script]
executable = "main.py"
icon = "helloworld.svg"

sources_folder = "src" # contains source scripts like: src/main.py, src/helloworld_module.py ...
assets_folder = "assets" # contains assets like: image,video,sound,binary,text data etc. in paket folder. like: assets/img/logo.png, assets/sound/intro.ogg, assets/3d_objects/My3DModel.obj